language: android
jdk:
  - oraclejdk8
sudo: false
env:
  global:
  - COMPILE_SDK_VERSION = 25
  - BUILD_TOOLS_VERSION = 25.0.3
android:
  components:
  - platform-tools
  - tools
  - build-tools-$BUILD_TOOLS_VERSION
  - android-$COMPILE_SDK_VERSION
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'
    - '.+'
notifications:
  email: false
before_install:
  - openssl aes-256-cbc -K $encrypted_98d43dcabc21_key -iv $encrypted_98d43dcabc21_iv
  -in keystore.jks.enc -out keystore.jks -d

before_script:
  - mkdir -p "$ANDROID_HOME/licenses"
  - cp ./android-licenses/ "$ANDROID_HOME/licenses/"

script:
  - ./gradlew build connectedCheck
