language: android

sudo: false

android:
  components:
    - build-tools-26.0.0
    - android-26
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - android-sdk-license-.+
    - '.+'

  notifications:
    email: false

script:
  - "./gradlew build connectedCheck"