language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - COMPILE_SDK_VERSION = 26
    - BUILD_TOOLS_VERSION = 26.0.1

android:
  components:
    - platform-tools
    - tools
    - build-tools-$BUILD_TOOLS_VERSION
    - android-$COMPILE_SDK_VERSION

  licenses:
    - android-sdk-license-.+
    - '.+'

  notifications:
    email: false

script:
  - ./gradlew build connectedCheck