language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.3
  - android-25
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-25
script:
- ./gradlew assembleRelease
before_install:
- openssl aes-256-cbc -K $encrypted_98d43dcabc21_key -iv $encrypted_98d43dcabc21_iv
  -in keystore.jks.enc -out keystore.jks -d
deploy:
  provider: releases
  api_key: db5b58fd961ccde48fb780460c0c275e3f528143
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true