language: android
jdk: oraclejdk8
sudo: false
env:
  global:
  - COMPILE_SDK_VERSION = 26
  - BUILD_TOOLS_VERSION = 26.0.1
android:
  components:
  - platform-tools
  - tools
  - build-tools-$BUILD_TOOLS_VERSION
  - android-$COMPILE_SDK_VERSION
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  licenses:
  - android-sdk-license-.+
  - .+
  notifications:
    email: false
script:
- ./gradlew build connectedCheck
before_install:
- openssl aes-256-cbc -K $encrypted_98d43dcabc21_key -iv $encrypted_98d43dcabc21_iv
  -in keystore.jks.enc -out keystore.jks -d
